### ISSUE TITLE
Visualization question

### ISSUE THREAD

**Issue by vwxyzjn** [arcman7/jssc2#16]
In the deepmind/pysc2 repo, it seems only the second visualization is enabled. May I ask how did you enable the first visualization? Is there a flag in the pysc2 repo?

![image](https://user-images.githubusercontent.com/5555347/93940946-69308600-fcfb-11ea-9c7f-57e563460120.png)

![image](https://user-images.githubusercontent.com/5555347/93941037-9aa95180-fcfb-11ea-8cab-1a8ead2efc1a.png)

Thanks.

**Comment by arcman7** [comment]
Hi there.

The relevant code to your question can be found on the following lines of `renderer_human.py`:
line 325   - `self._render_rgb = None`
line 378   - `self._render_rgb = False`
line 587   - `if self._render_rgb:`
line 1637 -  `if (self._render_rgb and self._obs.observation.HasField("render_data") and
        self._obs.observation.render_data.HasField("map")):`

As for any flag behavior that controls this, it would come from the game_info.options object in the field "render" (game_info.options.render) passed into the init method. It's `game_info.options.render` that causes `self._render_rgb` to be set to either `True` or `False`. See line 350 of renderer_human.py:
```
  def init(self, game_info, static_data):
    """Take the game info and the static data needed to set up the game.

    This must be called before render or get_actions for each game or restart.

    Args:
      game_info: A `sc_pb.ResponseGameInfo` object for this game.
      static_data: A `StaticData` object for this game.

    Raises:
      ValueError: if there is nothing to render.
    """
    self._game_info = game_info
    self._static_data = static_data

    if not game_info.HasField("start_raw"):
      raise ValueError("Raw observations are required for the renderer.")

    self._map_size = point.Point.build(game_info.start_raw.map_size)
    self._playable = point.Rect(
        point.Point.build(game_info.start_raw.playable_area.p0),
        point.Point.build(game_info.start_raw.playable_area.p1))

    if game_info.options.HasField("feature_layer"):
      fl_opts = game_info.options.feature_layer
      self._feature_screen_px = point.Point.build(fl_opts.resolution)
      self._feature_minimap_px = point.Point.build(fl_opts.minimap_resolution)
      self._feature_camera_width_world_units = fl_opts.width
      self._render_rgb = False
      if not fl_opts.crop_to_playable_area:
        self._playable = point.Rect(self._map_size)
    else:
      self._feature_screen_px = self._feature_minimap_px = None
    if game_info.options.HasField("render"):
      render_opts = game_info.options.render
      self._rgb_screen_px = point.Point.build(render_opts.resolution)
      self._rgb_minimap_px = point.Point.build(render_opts.minimap_resolution)
      self._render_rgb = True
```

That last bit there on line 387, `self._render_rgb = True`  is what would allow human_renderer to use the actual game rendering as opposed to reconstructing it in that rasterized form.

You should know, however, that both of those pictures you referenced were generated by the javascript version of the project, they are in fact rendered in the browser when the game is run with a human renderer enabled.

**Comment by vwxyzjn** [comment]
I see thank you for the help!

**Comment by arcman7** [comment]
I realized what you're probably after is this
`python -m pysc2.bin.agent --map Simple64 --rgb_screen_size 84 --rgb_minimap_size 64 --action_space RGB`

You can fiddle with the resolution via screen size and minimap size, as well as select different values for action_space (FEATURES|RGB|RAW)
